"""Create tables

Revision ID: 431f6642b14c
Revises: 
Create Date: 2021-07-04 15:18:10.070940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431f6642b14c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('subscription',
    sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('ad')
    # ### end Alembic commands ###
