"""Add UNIQUE constraint to the ad table

Revision ID: 8d4e5a45da75
Revises: e7f2692f0f50
Create Date: 2021-07-05 14:01:41.518984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4e5a45da75'
down_revision = 'e7f2692f0f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ad', ['subscription_id', 'url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ad', type_='unique')
    # ### end Alembic commands ###
