"""Add cascade delete all

Revision ID: 9bd876309631
Revises: 8d4e5a45da75
Create Date: 2021-07-07 15:33:48.673925

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9bd876309631'
down_revision = '8d4e5a45da75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ad_subscription_id_fkey', 'ad', type_='foreignkey')
    op.create_foreign_key(None, 'ad', 'subscription', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ad', type_='foreignkey')
    op.create_foreign_key('ad_subscription_id_fkey', 'ad', 'subscription', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
